# Generated by roxytest: do not edit by hand!

# File R/"07-diagnostics.R": @testexamples

test_that("Function br_diagnose() @ L42", {
  
  # Create models
  mds <- br_pipeline(
    survival::lung,
    y = c("time", "status"),
    x = colnames(survival::lung)[6:10],
    x2 = c("age", "sex"),
    method = "coxph"
  )
  
  # Diagnose models (includes PH testing for Cox models)
  diagnostics <- br_diagnose(mds)
  print(diagnostics)
  expect_s3_class(diagnostics, "br_diagnostics")
})


test_that("Function br_get_model_stats() @ L252", {
  
  m <- br_pipeline(survival::lung,
    y = c("time", "status"),
    x = colnames(survival::lung)[6:10],
    method = "coxph"
  )
  br_get_model_stats(m)
  expect_s3_class(br_get_model_stats(m), "data.frame")
})

