# Generated by roxytest: do not edit by hand!

# File R/"09-seed.R": @testexamples

test_that("Function br_seed_screen() @ L293", {
  
  
  set.seed(123)
  n <- 100
  # Create gene with real survival signal
  test_data <- data.frame(
    time = rexp(n, 0.1),
    status = sample(0:1, n, replace = TRUE),
    GENE1 = rnorm(n),
    GENE2 = rnorm(n, mean = 0.8 * (1:n) / n),
    GENE3 = rnorm(n),
    age = rnorm(n, 60, 10)
  )
  
  # Single survival indicator; use relaxed p_threshold for example data
  res <- br_seed_screen(test_data,
    y = c("time", "status"),
    y_type = "survival",
    genes = c("GENE1", "GENE2", "GENE3"),
    x2 = "age",
    p_threshold = 0.5
  )
  print(res)
  
  expect_s3_class(res, "breg_seed_screen")
  expect_true("genes" %in% names(res))
})


test_that("Function br_seed_select() @ L494", {
  
  
  set.seed(123)
  n <- 100
  test_data <- data.frame(
    time = rexp(n, 0.1),
    status = sample(0:1, n, replace = TRUE),
    GENE1 = rnorm(n),
    GENE2 = rnorm(n, mean = 0.8 * (1:n) / n),
    GENE3 = rnorm(n, mean = -0.5 * (1:n) / n),
    GENE4 = rnorm(n),
    GENE5 = rnorm(n),
    age = rnorm(n, 60, 10)
  )
  
  if (rlang::is_installed("glmnet")) {
    sel <- br_seed_select(test_data,
      y = c("time", "status"),
      y_type = "survival",
      genes = c("GENE1", "GENE2", "GENE3", "GENE4", "GENE5"),
      x2 = "age",
      seed = 42
    )
    print(sel)
  }
  
  if (rlang::is_installed("glmnet")) {
    expect_s3_class(sel, "breg_seed_select")
  }
})


test_that("Function br_seed_model() @ L706", {
  
  
  set.seed(123)
  n <- 100
  test_data <- data.frame(
    time = rexp(n, 0.1),
    status = sample(0:1, n, replace = TRUE),
    GENE1 = rnorm(n),
    GENE2 = rnorm(n, mean = 0.8 * (1:n) / n),
    GENE3 = rnorm(n, mean = -0.5 * (1:n) / n),
    age = rnorm(n, 60, 10)
  )
  
  mod <- br_seed_model(test_data,
    y = c("time", "status"),
    y_type = "survival",
    genes = c("GENE1", "GENE2", "GENE3"),
    x2 = "age"
  )
  print(mod)
  
  expect_s3_class(mod, "breg_seed_model")
})


test_that("Function br_seed() @ L918", {
  
  
  set.seed(123)
  n <- 100
  test_data <- data.frame(
    time = rexp(n, 0.1),
    status = sample(0:1, n, replace = TRUE),
    GENE1 = rnorm(n),
    GENE2 = rnorm(n, mean = 0.8 * (1:n) / n),
    GENE3 = rnorm(n, mean = -0.5 * (1:n) / n),
    GENE4 = rnorm(n),
    GENE5 = rnorm(n),
    age = rnorm(n, 60, 10)
  )
  
  if (rlang::is_installed("glmnet")) {
    res <- br_seed(test_data,
      y = c("time", "status"),
      y_type = "survival",
      genes = c("GENE1", "GENE2", "GENE3", "GENE4", "GENE5"),
      x2 = "age",
      p_threshold = 0.3,
      seed = 42
    )
    print(res)
  }
  
  if (rlang::is_installed("glmnet")) {
    expect_s3_class(res, "breg_seed")
  }
})

