# Generated by roxytest: do not edit by hand!

# File R/"03-accessors.R": @testexamples

test_that("[unknown alias] @ L50", {
  
  m <- br_pipeline(mtcars,
    y = "mpg",
    x = colnames(mtcars)[2:4],
    x2 = "vs",
    method = "gaussian"
  )
  br_get_data(m)
  br_get_y(m)
  br_get_x(m)
  br_get_n_x(m)
  br_get_x2(m)
  br_get_n_x2(m)
  br_get_group_by(m)
  br_get_config(m)
  br_get_models(m)
  br_get_models(m, 1)
  br_get_n_x2(m)
  br_get_results(m)
  br_get_results(m, tidy = TRUE)
  br_get_results(m, tidy = TRUE, term == "cyl")
  
  assert_breg_obj_with_results(m)
})

